### ISSUE TITLE
To do list for new version

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#1]
In no particular order:

* Multicore argument:
 * [BOB] Test the multicore argument some more to see if it can be used to speed things up
 * [JAMIE] Ask around to see if people have used the 'multicore' argument and if it is worthwhile

* Parallelization:
 * [JAMIE] Investigate the parallelization question and see how difficult this is to complete

* Passing arguments through dismo:
 * [BOB] Test the "noaddsamplestobackground" issue raised by Ahmed

* Adding model objects to ENMevaluation object + Wallace compatability
 * [JAMIE + BOB] Test Jamie's edits  to make sure they work consistently... (especially the new save to model objects aspect) 

* Documentation edits:
 * [BOB] Change note in get.user example to: "# NOTE: BACKGROUND PARTITIONS ARE USER-DEFINED"
 * [BOB] Add Burnham & Anderson et al. 2011 reference on AICc (delta AICc < 2) stuff

**Comment by ndimhypervol** [comment]
Thanks for posting this Bob -- very helpful! I'll get to the stuff on my end.

**Comment by ndimhypervol** [comment]
Bob, just implemented parallel computing. I had to rearrange a bunch of stuff to make the "foreach" function play along with the rest of the code. However, it works fine, as far as I can tell, and even with a very tiny dataset that I was using as an example, it was 35% faster. I'd be very curious to see it perform on a bigger one, but I want to sleep. Could you test it out a little? You need to turn it on with "parallel=TRUE" in the params.

**Comment by bobmuscarella** [comment]
awesome, man!   I will look at this and do some testing...  get back to you
soon...

**Comment by bobmuscarella** [comment]
Awesome!

The parallel option can definitely speed things up but it depends on the size of the analysis.  With small analyses, it takes longer to get the parallelization set up than to just run it normally.  I think with most real life analyses, however, it will be faster to use parallel option.

Using the simulated data from the package examples, here are some examples:

**"Small analysis"** (*slower with parallel*)
> enmeval_results1 <- ENMevaluate(occ, env, categoricals=4, method="checkerboard1", n.bg=500, rasterPreds=F, RMvalues=c(1:2), fc=c("L","LQ"))

Without parellel = 7.13 seconds
With parellel = 16.6 seconds

**"Big analysis"** (*faster with parallel*)
> enmeval_results1 <- ENMevaluate(occ, env, categoricals=4, method="checkerboard1", n.bg=500, rasterPreds=T)

Without parellel = 3.17 minutes
With parellel = 2.41 minutes

I don't know the best way to give a standarized way of quantifying this tradeoff in time?  It may be easiest to just provide an example somewhere... (time to start thinking more about a vignette....)

**Comment by ndimhypervol** [comment]
Interesting. We could perhaps throw a warning up that parallel may take a bit longer if we see that there aren't many runs to do and the dataset's small. I did some comparisons on a much larger dataset with lots of iterations, and it was significantly faster -- I'm guessing the benefit increases geometrically with more data and runs. Also depends on how many cores you have -- I was using 4. Regardless, we could throw up a warning or something. And surely put it in a vignette!

**Comment by bobmuscarella** [comment]
For now I think we can simply comment on this in the documentation for the parallel option.  I think it will speed things up in most cases so we can probably just say, "for very small analyses, it is possible that running with parallel=T will take longer than with parallel=F."
