### ISSUE TITLE
Vignette Table of Contents

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#11]
INPUT
1. Loading and input data (Radoslovich data?, trees, or simulated?)
- Getting climatic data 

OPTIONS
-  Partitioning methods (including user-defined!)

RUN ENMevaluate

PLOTTING RESULTS
- Plot complex versus smooth models to see effect
- Talk about evaluation metrics (table from paper)
- Options for selecting optimal models

DOWNSTREAM 
- Plotting response curves
  - Use `response(ENMeval_results@models[[1]])`
- Extracting model results from object (various threshold)
- Use model object to make a new prediction if you want a logistic prediction
- Make a projection to a new extent
- Do MESS map 
  - Use `mess()` is dismo

**Comment by ndimhypervol** [comment]
Started this, finally. Find it in /vignettes. I'm writing it in rmarkdown format, which is a real pleasure. I've started it along, but we should decide what sections each of us should author, etc. By the way, I've found this page very [helpful](http://r-pkgs.had.co.nz/vignettes.html).
