### ISSUE TITLE
Put message saying, "working" and then report time when done for parallel

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#13]

**Comment by bobmuscarella** [comment]
I started work on this but I realized that I didn't want to accidentally mess up anything in the parallel code (which I don't fully understand) when deleting the progress bar stuff.  SO, I'm wondering if you could take care of the following items?

1) Delete all the progress bar stuff when running in parallel (but keep the old progress bar when not running in parallel).
2) Add a message when running parallel ('Working in parallel... please wait') and print system time when completed for both parallel and not parallel runs.
3) Remove all code for progress bar that was used exclusively for Wallace stuff.

**Comment by ndimhypervol** [comment]
I've already removed the WALLACE progress bar stuff from "edits2015", and I'm leaving it in "edits". As for the progress text file, I can remove that and add a simple message instead. I'll try to get to that today.

**Comment by ndimhypervol** [comment]
All done. Check on my new commits and close if this is complete.

**Comment by bobmuscarella** [comment]
Looks good... I just changed the "cat" functions to "message" so that the text appears in red.  Thanks!
