### ISSUE TITLE
Test with various datasets

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#15]

**Comment by bobmuscarella** [comment]
Simulated data used in examples seems to work fine

**Comment by ndimhypervol** [comment]
Great. Would that be sufficient for testing? I can download some big GBIF dataset and test that too.

**Comment by bobmuscarella** [comment]
I've tested also with the PR tree analysis and it works.  I'm mostly concerned that we do a couple of checks on a PC since I've only tested on a mac.   

Once you convince yourself that PC testing is adequate then we can close this issue.

**Comment by bobmuscarella** [comment]
I managed to do some testing on PC and it seems to work fine except that when running in parallel, the messages do not get printed until AFTER the run is completed.  I'm not sure how/if there is a way to fix this...

**Comment by ndimhypervol** [comment]
I can look into this today at the lab.

**Comment by bobmuscarella** [comment]
Any progress with this?  The issue I reported on a PC may be related to the fact that I'm running it on a PC via a remote desktop so things are kind of strange...  I think it's pretty much ready to push to CRAN once you give the OK on PC testing...

**Comment by ndimhypervol** [comment]
Oops, let this slip - sorry! Let me put this on my calendar for tomorrow to check out. I'll get back to you.

**Comment by bobmuscarella** [comment]
Hey Jamie -
I'm just following up on this in the Wallace aftermath!  The status, it
seems, is that we can finalize this after a couple checks on a PC.  I've
used it now to re-run all the PR tree models and it works but I'd like to
get your sign off on it, too, before pushing it out.  Anyway, hopefully we
can get it done this week - what do you say?
Bob

**Comment by ndimhypervol** [comment]
Bob,

I will test on PC today and report back later. I agree -- the faster this
gets out the better!

-J

On 8 September 2015 at 09:28, Bob Muscarella <notifications@github.com>
wrote:

> Hey Jamie -
> I'm just following up on this in the Wallace aftermath! The status, it
> seems, is that we can finalize this after a couple checks on a PC. I've
> used it now to re-run all the PR tree models and it works but I'd like to
> get your sign off on it, too, before pushing it out. Anyway, hopefully we
> can get it done this week - what do you say?
> Bob
>
> On Sat, Aug 29, 2015 at 7:54 PM, Jamie M. Kass <notifications@github.com>
> wrote:
>
> > Oops, let this slip - sorry! Let me put this on my calendar for tomorrow
> > to check out. I'll get back to you.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/bobmuscarella/ENMeval/issues/15#issuecomment-136071330>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bobmuscarella/ENMeval/issues/15#issuecomment-138558918>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by ndimhypervol** [comment]
I tested it on the PC here and everything worked just fine. Used a small dataset with a good number of iterations (3 FCs, 3 RMs). The first run with parallel was a little slow, but the next few runs were faster (2x) than without. The time reported correctly, and since I took out the file for the time log, I think everything's in order.
