### ISSUE TITLE
tuning function is broken

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#16]
Something seems to have gotten messed up while I was trying to get rid of 'updateProgress' stuff.  It seems there is a missing close curly bracket ( "}" ) somewhere but I am not sure where it goes in order to not screw up the parallel code...

Need help with this Jamie!

**Comment by ndimhypervol** [comment]
Think I fixed this. There was an extra bracket where I deleted the updateProgress stuff. Oops.
