### ISSUE TITLE
Venues for advertising new version

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#17]
Let's brainstorm a list here of where to post:

1) Maxent Google Groups
2) Notify Rob and other co-authors on the package to post to whatever lists they have
3) AMNH SDM group
4) Labs in the area (and beyond) we know that use this stuff: Graham, Akcakaya, Carnaval, Uriarte, etc.
5) ???

**Comment by bobmuscarella** [comment]
Jamie: here is the message I'm planning to post to the Maxent Google Group (and elsewhere).  Let me know if you have edits/additions.  

=====
**ENMeval v 0.2.0 now on CRAN - Featuring Parallel Processing!!!**

A new version (0.2.0) of the ENMeval R package is now available on CRAN (https://cran.r-project.org/web/packages/ENMeval/index.html).  The main change (led by Jamie Kass) is the implementation of a parallel processing option that can significantly speed up run times.  See documentation for ENMevaluate for more details.

Additional significant changes include:
 - Added a "models" slot in ENMevaluation object class to hold Maxent model objects.  This allows the user to access the lambda values and original results table generated by Maxent.
 - Fixed a bug that allowed only a single categorical variable; now multiple categorical variables work.
 - Added an argument in the ENMevaluate function to turn off raster prediction generation to save time (default is rasterPreds=TRUE).

As always, please let me and Jamie know if you encounter any bugs or have particular requests for future functionality. 

Hope you find it helpful in your work,
Bob

**Comment by ndimhypervol** [comment]
My changes:

*ENMeval v 0.2.0 now on CRAN - Featuring Parallel Processing!!!*

A new version (0.2.0) of the ENMeval R package is now available on CRAN (
https://cran.r-project.org/web/packages/ENMeval/index.html). The main
change (led by Jamie Kass) is the implementation of a parallel processing
option that can significantly speed up run times. See documentation for
ENMevaluate for more details.

Additional significant changes include:

   - Added a "models" slot in ENMevaluation object class to hold Maxent
   model objects. This allows the user to access the lambda values and
   original results table generated by Maxent, and use the predict()
   function to create logistic predictions and project the model to new areas
   and/or time periods.
   - Fixed a bug that allowed only a single categorical variable; now
   multiple categorical variables work.
   - Added an argument in the ENMevaluate function to turn off raster
   prediction generation to save time (default is rasterPreds=TRUE).

As always, please let me and Jamie know if you encounter any bugs or have
particular requests for future functionality.

Hope you find it helpful in your work,
Bob

On 9 September 2015 at 12:07, Bob Muscarella <notifications@github.com>
wrote:

> Jamie: here is the message I'm planning to post to the Maxent Google Group
> (and elsewhere). Let me know if you have edits/additions.
>
> *ENMeval v 0.2.0 now on CRAN - Featuring Parallel Processing!!!*
>
> A new version (0.2.0) of the ENMeval R package is now available on CRAN (
> https://cran.r-project.org/web/packages/ENMeval/index.html). The main
> change (led by Jamie Kass) is the implementation of a parallel processing
> option that can significantly speed up run times. See documentation for
> ENMevaluate for more details.
>
> Additional significant changes include:
>
>    - Added a "models" slot in ENMevaluation object class to hold Maxent
>    model objects. This allows the user to access the lambda values and
>    original results table generated by Maxent.
>    - Fixed a bug that allowed only a single categorical variable; now
>    multiple categorical variables work.
>    - Added an argument in the ENMevaluate function to turn off raster
>    prediction generation to save time (default is rasterPreds=TRUE).
>
> As always, please let me and Jamie know if you encounter any bugs or have
> particular requests for future functionality.
>
> Hope you find it helpful in your work,
> Bob
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bobmuscarella/ENMeval/issues/17#issuecomment-138958328>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by bobmuscarella** [comment]
Posted to google groups, emailed Rob, emailed Mary Blair for posting to NY SDM group...
