### ISSUE TITLE
Version number (2.0) and DESCRIPTION file

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#18]
A couple little notes for you...  go ahead and close this once you check it out if you have no problems.

- I changed the new version number to 2.0 - I think  3 numbers seem overkill.  
- To get through the CRAN Check with no notes or errors, I had to make some changes to the DESCRIPTION and NAMESPACE files - no big deal.

**Comment by ndimhypervol** [comment]
Got it. Sounds good.
