### ISSUE TITLE
Problem when number of eval bins < number expected

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#20]
This came up for me when using the checkerboard method and some bins did not have any occurrence records.  In this case, you can get an error via the loop in tuning that starts...

`for (k in nk)`

For instance, image that bin 2 has no occurrence records.  The valid bins are then [1,3,4] and an error pops up during the evaluation of bin 2.  

I attempted a couple fixes and realized that it is desirable to keep the group names consecutive even if missing a bin because using the 'k' counter is nice for filling in columns.  

I think the edits I made to `checkerboard1` and `checkerboard2` functions fix this (at least if there are missing bins for occurrence).  I also added a couple warning messages to let the user know if there are fewer than expected groups.  I don't see how this could be a problem with any of the other partitioning methods but let me know if you can think of why it might occur...  (Although I suppose it could happen with the 'user-specified' method if the user specifies groups in non-sequential order...).

A limitation of this fix is the unlikely case that occurrence records fill all bins but background points do not.  I think this will occur too often and for now I've implemented an error in this case.  I think this is rare event only but there is surely a better way of dealing with this in the future....

**Comment by bobmuscarella** [comment]
I've tested this and think it works although, as mentioned above, not the best solution.  Future edits may find something more elegant...

**Comment by ndimhypervol** [comment]
I like your method, but I can't imagine as well how you'd get no background
pts in checkerboard bins, unless you chose very few on purpose. The message
is not exactly accurate, because it's really that the number of bins
background pts fall in is not equal to that of occ pts, right? Pretty minor
though.

On 9 September 2015 at 11:51, Bob Muscarella <notifications@github.com>
wrote:

> Closed #20 <https://github.com/bobmuscarella/ENMeval/issues/20>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bobmuscarella/ENMeval/issues/20#event-404984052>.
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by bobmuscarella** [comment]
True - I changed the message there to:
"Error: occurrence records but no background points fall in 1 or more evaluation bin(s)"
