### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#22]
I just pulled edits2015 branch to master.  I then forked the new master to a branch called "Version-0.2.0" for archival purposes.  We also have archive branches for Versions 0.1.1 and 0.1.2.  

SO, is it fine by you to:
- **DELETE** "edits2015" and "edits" 
- **KEEP** Master and archival branches "Version 0.1.1","Version 0.1.2", "Version 0.2.0"

? Am I understanding use of branches okay???

**Comment by ndimhypervol** [comment]
Yes, that seems appropriate. Then, when we want to do more editing, we can
just checkout a new branch from an archival one. But don't delete "edits"
yet though -- Wallace still uses it. Let's keep it around for a little bit
longer. We can delete edits2015 if it's already archived though.

On 9 September 2015 at 16:46, Bob Muscarella <notifications@github.com>
wrote:

> I just pulled edits2015 branch to master. I then forked the new master to
> a branch called "Version-0.2.0" for archival purposes. We also have archive
> branches for Versions 0.1.1 and 0.1.2.
>
> SO, is it fine by you to:
>
>    - *DELETE* "edits2015" and "edits"
>    - *KEEP* Master and archival branches "Version 0.1.1","Version 0.1.2",
>    "Version 0.2.0"
>
> ? Am I understanding use of branches okay???
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bobmuscarella/ENMeval/issues/22>.
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC
