### ISSUE TITLE
Allow all maxent args to be passed (e.g., prevelance)

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#30]
We should add a ... argument to the ENMevaluate function that allows other options to be passed to maxent (e.g. prevalence).  This will require changes to the ENMevaluate, tuning, and make.args functions.

**From Xavier Rotllan-Puig:**
"I have modified ENMevaluate.R and make.args.R in order to be able to modify the parameter "prevalence" to be passed to maxent."

**From Jamie:**
"...I think to avoid adding too many extra parameters, we might want to simply add a "..." parameter to allow users to input any maxent-related parameter they'd like."

**Comment by ndimhypervol** [comment]
Yes, exactly. And the only function to use the ... would be maxent().
Therefore, I think it's an easy fix.

On 8 October 2015 at 09:21, Bob Muscarella <notifications@github.com> wrote:

> We should add a ... argument to the ENMevaluate function that allows other
> options to be passed to maxent (e.g. prevalence). This will require changes
> to the ENMevaluate, tuning, and make.args functions.
>
> *From Xavier Rotllan-Puig:*
> "I have modified ENMevaluate.R and make.args.R in order to be able to
> modify the parameter "prevalence" to be passed to maxent."
>
> *From Jamie:*
> "...I think to avoid adding too many extra parameters, we might want to
> simply add a "..." parameter to allow users to input any maxent-related
> parameter they'd like."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bobmuscarella/ENMeval/issues/30>.
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by ndimhypervol** [comment]
Bob, see my new edits to the Edits_on_v.0.2.1 branch. I ran it with and without parallel with the arg "defaultprevalence" equal to 0.2, and it worked alright.

**Comment by bobmuscarella** [comment]
It looks like arguments that take numeric values are okay but I ran into problems with things that require 'true'.  For instance, this seemed to work:
```r
> res <- ENMevaluate(occ, env, method='block', n.bg=500, RM=2, fc=c('L'), defaultprevalence=.9)
```
But this didn't:
```r
> res <- ENMevaluate(occ, env, method='block', n.bg=500, RM=2, fc=c('L'), doclamp=true)

Error in ENMevaluate(occ, env, method = "block", n.bg = 500, RM = 2, fc = c("L"),  : 
  object 'true' not found
```

Can think of a way around this? 

In any case, some things are not relevant to what ENMeval does - like the option to draw response curves in the .html file is irrelevant unless we start allowing an option to save the html files somewhere.  Also, some of the arguments are duplicated by the ENMeval arguments (i.e., 'betamultiplier').  **I think we should make a more narrow list of arguments that are novel (to ENMeval) and then add those as explicit arguments.**

Below, I have separated arguments from the list you added into 2 categories (Should include + Would be nice but won't work right now).  The codes in parentheses stand for B=boolean, N=numeric, C=character.  The Numeric arguments appear to work in the way you already implemented but it seems we have to find a different solution to get the Boolean and Character arguments to work (like add them as explicit arguments).

**These things seem relevant and good to include (although some more important than others):**
- addallsamplestobackground (B)
- addsamlpestobackground (B)
- allowpartialdata (B)
- beta_categorical (N)
- beta_hinge (N)
- beta_lqp (N)
- beta_threshold (N)
- defaultprevalence (N)
- extrapolate (B)
- fadebyclamping (B)
- jackknife (B)
- outputformat (C)
- removeduplicates (B)
- convergencethreshold (N)
- maximumiterations (N)

**These could be nice but won't work as things are currently implemented (either because of ENMeval or dismo):**
- biasfile (C)
- outputdirectory (C)
- writeclampgrid (B)
- writemess (B)

*What do you think?*

**Comment by ndimhypervol** [comment]
Hm, I like this idea. I think we should code this up. We should also think
about a way to include generating a MESS map somehow, or at least point the
user to this functionality elsewhere (I think dismo can do it).

On 21 October 2015 at 11:52, Bob Muscarella <notifications@github.com>
wrote:

> It looks like arguments that take numeric values are okay but I ran into
> problems with things that require 'true'. For instance, this seemed to work:
>
> > res <- ENMevaluate(occ, env, method='block', n.bg=500, RM=2, fc=c('L'), defaultprevalence=.9)
>
> But this didn't:
>
> > res <- ENMevaluate(occ, env, method='block', n.bg=500, RM=2, fc=c('L'), doclamp=true)
> Error in ENMevaluate(occ, env, method = "block", n.bg = 500, RM = 2, fc = c("L"),  :
>   object 'true' not found
>
> Can think of a way around this?
>
> In any case, some things are not relevant to what ENMeval does - like the
> option to draw response curves in the .html file is irrelevant unless we
> start allowing an option to save the html files somewhere. Also, some of
> the arguments are duplicated by the ENMeval arguments (i.e.,
> 'betamultiplier'). *I think we should make a more narrow list of
> arguments that are novel (to ENMeval) and then add those as explicit
> arguments.*
>
> Below, I have separated arguments from the list you added into 2
> categories (Should include + Would be nice but won't work right now). The
> codes in parentheses stand for B=boolean, N=numeric, C=character. The
> Numeric arguments appear to work in the way you already implemented but it
> seems we have to find a different solution to get the Boolean and Character
> arguments to work (like add them as explicit arguments).
>
> *These things seem relevant and good to include (although some more
> important than others):*
>
>    - addallsamplestobackground (B)
>    - addsamlpestobackground (B)
>    - allowpartialdata (B)
>    - beta_categorical (N)
>    - beta_hinge (N)
>    - beta_lqp (N)
>    - beta_threshold (N)
>    - defaultprevalence (N)
>    - extrapolate (B)
>    - fadebyclamping (B)
>    - jackknife (B)
>    - outputformat (C)
>    - removeduplicates (B)
>    - convergencethreshold (N)
>    - maximumiterations (N)
>
> *These could be nice but won't work as things are currently implemented
> (either because of ENMeval or dismo):*
>
>    - biasfile (C)
>    - outputdirectory (C)
>    - writeclampgrid (B)
>    - writemess (B)
>
> *What do you think?*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bobmuscarella/ENMeval/issues/30#issuecomment-149940691>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by bobmuscarella** [comment]
Yes - you're right.  You can do it in dismo with `mess()`.  I guess this is another thing to add to the Table Of Contents...

**Comment by ndimhypervol** [comment]
Yeah, and we can write this all into a vignette, maybe over the winter?
