### ISSUE TITLE
Error in txtProgressBar (from Madeline Steele)

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#31]
The following was emailed by Madeline Steele <madeline.steele@gmail.com>:

> Hello again Bob and Jamie, 
I thought I should let you know that I've gotten the following error a few times now:
```r
Of 8 total cores using 8
Running in parallel...
Calculating niche overlap
Error in txtProgressBar(0, nlayers(predictive.maps) - 1, style = 3) : 
  must have 'max' > 'min'
```

> This only seems to happen when I use rasterPreds=FALSE.  If it's set to TRUE, there is no issue and it runs fine.

**Comment by ndimhypervol** [comment]
Madeline,
I'm not sure what version you're using, because I can't find that line anywhere. The line should read:
line 110 |      pb <- txtProgressBar(0, length(maxent.args), style = 3) 
Are you using an old version? Did you modify the script?

**Comment by bobmuscarella** [comment]
This line is in the `calc.niche.overlap()` function.  The real problem is that niche overlap stats cannot be calculated if rasterPreds=F because they are directly used ("niche overlap" stats are based on overlap in geographic space).

I added a message to the part of the ENMevaluate function that should warn the user about this and it skips the calculation (same thing as if `!length(maxent.args) >  1`)
