### ISSUE TITLE
Save all or part of HTML files...

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#33]
User's may be interested in the HTML files because:
1) That's what they're familiar with reading
2) They want to see the response curves
3) Other...

We could provide an option to:
1) Save the actual HTML file (this also requires saving all the other files generated)
- I don't think this is the best option since it would be a file management nightmare and not easily usable by the user anyway.

2) Somehow convert the HTML files into, say, PDFs and print them as a multipage PDF...
- This may be nice if just visualizing the results is the goal.  None of the data would be directly available and not sure how much use this would actually get.  I'm not sure how to go from the HTML file to save as a PDF, either, but it must be possible...?

3) Save the data from the response curves into the ENMevaluate object and make a function to plot the response curves.  
- Writing the response curves takes additional time and I guess it makes sense only to do it for the "full" model (rather than each run of the k-fold iterations for evaluation).  This would also get to be a complex thing:  imagine 20 different model settings x 10 input variables each x response with and without other variables held constant...  anyways, this would achieved by getting the plot data before deleting the maxent files...

```r
# Add these options to the args passed to dismo::maxent
...args=c('writeplotdata=true','responsecurves=true')

# Assuming the model object is called, 'fullmod', get the response curve data for plotting:
plotfiles <- list.files(paste(fullmod@path, 'plots', sep='/'))
resp <- data.frame()
for (i in plotfiles[grep('.dat', plotfiles)]){
	tmp <- read.csv(paste(me@path, 'plots', i, sep='/'))
	tmp$file <- i
	resp <- rbind(resp, tmp)
}

# Then the plotting could happen something like this:
plot(resp[,2][resp$file== plotdat[i]], resp[,3][resp$file==plotdat[i]], xlab=plotdat[i], type='l', col=2, lwd=3, ylab='Maxent Output')

```

**Comment by ndimhypervol** [comment]
I'm pretty sure you can plot the response curves by doing response(mx) if
mx is the model object. I don't like offering the HTML files because
besides being a file management nightmare, all the info they need is in the
model object. Instead, we can make a vignette that shows them how to plot
all the things they want.

On 6 November 2015 at 04:44, Bob Muscarella <notifications@github.com>
wrote:

> User's may be interested in the HTML files because:
> 1) That's what they're familiar with reading
> 2) They want to see the response curves
> 3) Other...
>
> We could provide an option to:
> 1) Save the actual HTML file (this also requires saving all the other
> files generated)
>
>    - I don't think this is the best option since it would be a file
>    management nightmare and not easily usable by the user anyway.
>
> 2) Somehow convert the HTML files into, say, PDFs and print them as a
> multipage PDF...
>
>    - This may be nice if just visualizing the results is the goal. None
>    of the data would be directly available and not sure how much use this
>    would actually get. I'm not sure how to go from the HTML file to save as a
>    PDF, either, but it must be possible...?
>
> 3) Save the data from the response curves into the ENMevaluate object and
> make a function to plot the response curves.
>
>    - Writing the response curves takes additional time and I guess it
>    makes sense only to do it for the "full" model (rather than each run of the
>    k-fold iterations for evaluation). This would also get to be a complex
>    thing: imagine 20 different model settings x 10 input variables each x
>    response with and without other variables held constant... anyways, this
>    would achieved by getting the plot data before deleting the maxent files...
>
> # Add these options to the args passed to dismo::maxent...args=c('writeplotdata=true','responsecurves=true')
> # Assuming the model object is called, 'fullmod', get the response curve data for plotting:plotfiles <- list.files(paste(fullmod@path, 'plots', sep='/'))resp <- data.frame()for (i in plotfiles[grep('.dat', plotfiles)]){
>     tmp <- read.csv(paste(me@path, 'plots', i, sep='/'))
>     tmp$file <- i
>     resp <- rbind(resp, tmp)
> }
> # Then the plotting could happen something like this:
> plot(resp[,2][resp$file== plotdat[i]], resp[,3][resp$file==plotdat[i]], xlab=plotdat[i], type='l', col=2, lwd=3, ylab='Maxent Output')
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bobmuscarella/ENMeval/issues/33>.
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by bobmuscarella** [comment]
Word.
I didn't know about `response(model)` but, you're right and it works fine with ENMeval models!
I agree that the best option is to point this out and to add this kind of stuff to the vignette... I'll add a bullet point to that Table Of Contents now...
Bob
