### ISSUE TITLE
Address CRAN error

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#35]
I had to make some edits to the NAMESPACE to comply with CRAN admin.  For some reason, the current version of R (3.2.3) was giving a warning when doing the check for (all except Mavericks OS).  The problem was:

> Maintainer: Robert Muscarella <bob.muscarella@gmail.com>
Package: ENMeval Version: 0.2.0
Check: whether package can be installed ... WARNING
  Found the following significant warnings:
    Warning: replacing previous import ‘raster::plot’ by ‘graphics::plot’ when loading ‘ENMeval’
  See ‘/home/hornik/tmp/R.check/r-devel-gcc/Work/PKGS/ENMeval.Rcheck/00install.out’ for details.
See: <http://CRAN.R-project.org/web/checks/check_results_ENMeval.html>

Since we only use a handful of functions from `raster`, I:
1) Moved raster from 'depends' to 'imports' in the DESCRIPTION
2) Deleted raster from the Imports section of NAMESPACE
3) Added raster to a new line in NAMESPACE:
`importFrom("raster", "cellStats", "extract", "nlayers", "aggregate", "stack")`

I used the WinBuilder utility to check the new version on a PC and it got through with no warnings.
http://win-builder.r-project.org/upload.aspx

This is good anyway because we still have v.0.2.0 on CRAN (for some reason they didn't update with our previous version of 0.2.1, which fixed the issue about results table mislabelling columns when bin.output=T).

I made these changes to the V.0.2.1 branch, pulled those into master (which is currently v0.2.1) and also added these changes to the 'edits_on_v0.2.1' branch, which is the current working branch.

**Comment by ndimhypervol** [comment]
Sounds good, Bob!

On 4 January 2016 at 10:04, Bob Muscarella <notifications@github.com> wrote:

> Closed #35 <https://github.com/bobmuscarella/ENMeval/issues/35>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bobmuscarella/ENMeval/issues/35#event-504837012>.
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC
