### ISSUE TITLE
avoid non-numeric rownames in ENMevaluate

### ISSUE THREAD

**Issue by ptitle** [bobmuscarella/ENMeval#36]
In running ENMevaluate, I was getting the following warning:
`Warning in order(as.numeric(rownames(r))) : NAs introduced by coercion`

I tracked it down to the fact that, due to prior manipulations, the rownames of my occurrences data.frame were V1, V2, V3, etc. In the function, get.block() (and presumably in other functions in the package), the data.frame `r` is numerically reordered with `r[order(as.numeric(rownames(r))), ]$grp`, and as the rownames have a character in them, the warning is generated. 

Although this is easily fixed by me changing my rownames, this warning would be generally avoided if the rownames of the occ data.frame are replaced with 1:nrow(occ).

**Comment by ndimhypervol** [comment]
Good point. We could make that change pretty easily in the next version. Thanks for pointing that out.

**Comment by bobmuscarella** [comment]
I added these lines to the get.partitioning methods:

  occ <- as.data.frame(occ)
  rownames(occ) <- 1:nrow(occ)
  bg.coords <- as.data.frame(bg.coords)
  rownames(bg.coords) <- 1:nrow(bg.coords)
