### ISSUE TITLE
Dimensions of get.block output do not match input dimensions (occ and bg.coords)

### ISSUE THREAD

**Issue by tysonwepprich** [bobmuscarella/ENMeval#38]
I think this is a simple fix. In the following lines in get.block, the min and max values should be wrapped in c(), otherwise mean just returns the first argument without averaging them. This caused some coordinates to be dropped in the subsequent splitting.

    bvert <- mean(max(grp1[, 1]), min(grp2[, 1])) # bvert <- mean(c(max(grp1[, 1]), min(grp2[, 1])))
    tvert <- mean(max(grp3[, 1]), min(grp4[, 1]))
    horz <- mean(max(grpA[, 2]), min(grpB[, 2]))

**Comment by bobmuscarella** [comment]
Thanks for that, Tyson.

Jamie - I will make the changes to the current edits branch.  Let me know if you have any objections.

**Comment by ndimhypervol** [comment]
Nope, this is an easy fix. Thanks for tackling this, Bob.

On 4 April 2016 at 10:17, Bob Muscarella <notifications@github.com> wrote:

> Thanks for that, Tyson.
>
> Jamie - I will make the changes to the current edits branch. Let me know
> if you have any objections.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bobmuscarella/ENMeval/issues/38#issuecomment-205315097>
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC
