### ISSUE TITLE
error with getcheckerboard2() from Cory

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#39]
***FROM CORY:***
also, i noticed that getcheckerboard2 gives me an error when assigning ww$grp=1. my input points and bg are both matrices, so the outputs of gridSample() are matrices, so when you assign ww$grp=1, its expecting ww to be a data.frame (i'm guessing it is if you input a data.frame). if ww isn't a dataframe, this line turns ww into a list, which messes up rbind. so my dumb solution below is just to make all the samples clunky dataframes. sorry to be a whiner...
cory

get.checkerboard2.cm=function (occ, env, bg.coords, aggregation.factor) 
{ 
if (length(aggregation.factor) == 1) 
        aggregation.factor <- rep(aggregation.factor, 2)
    grid <- aggregate(env[[1]], fact = aggregation.factor[1])
    grid2 <- aggregate(grid, aggregation.factor[2])
    w <- data.frame(gridSample(occ, grid, n = 10000, chess = "white"))
    b <- data.frame(gridSample(occ, grid, n = 10000, chess = "black"))
    ww <- data.frame(gridSample(w, grid2, n = 10000, chess = "white"))
    wb <- data.frame(gridSample(w, grid2, n = 10000, chess = "black"))
    bw <- data.frame(gridSample(b, grid2, n = 10000, chess = "white"))
    bb <- data.frame(gridSample(b, grid2, n = 10000, chess = "black"))
    bgw <- data.frame(gridSample(bg.coords, grid, n = 10000, chess = "white"))
    bgb <- data.frame(gridSample(bg.coords, grid, n = 10000, chess = "black"))
    bgww <- data.frame(gridSample(bgw, grid2, n = 10000, chess = "white"))
    bgwb <- data.frame(gridSample(bgw, grid2, n = 10000, chess = "black"))
    bgbw <- data.frame(gridSample(bgb, grid2, n = 10000, chess = "white"))
    bgbb <- data.frame(gridSample(bgb, grid2, n = 10000, chess = "black"))
    r <- data.frame()
    if (nrow(ww) > 0) 
        ww$grp <- 1
    r <- rbind(r, ww)
    if (nrow(wb) > 0) 
        wb$grp <- 2
    r <- rbind(r, wb)
    if (nrow(bw) > 0) 
        bw$grp <- 3
    r <- rbind(r, bw)
    if (nrow(bb) > 0) 
        bb$grp <- 4
    r <- rbind(r, bb)
    occ.grp <- r[order(as.numeric(rownames(r))), ]$grp
    bgr <- data.frame()
    if (nrow(bgww) > 0) 
        bgww$grp <- 1
    bgr <- rbind(bgr, bgww)
    if (nrow(bgwb) > 0) 
        bgwb$grp <- 2
    bgr <- rbind(bgr, bgwb)
    if (nrow(bgbw) > 0) 
        bgbw$grp <- 3
    bgr <- rbind(bgr, bgbw)
    if (nrow(bgbb) > 0) 
        bgbb$grp <- 4
    bgr <- rbind(bgr, bgbb)
    bg.grp <- bgr[order(as.numeric(rownames(bgr))), ]$grp
    noccgrp <- length(unique(occ.grp))
    nbggrp <- length(unique(bg.grp))
    if (noccgrp < 4) {
        message(paste("Warning: occurrence points fall in only", 
            noccgrp, "bins"))
        bg.grp[!bg.grp %in% occ.grp] <- NA
        occ.grp <- as.numeric(as.factor(occ.grp))
        bg.grp <- as.numeric(as.factor(bg.grp))
    }
    if (length(unique(bg.grp[!is.na(bg.grp)])) != noccgrp) {
        message("Error: occurrence records but no background points fall in 1 or more evaluation bin(s)")
        stop()
    }
    out <- list(occ.grp = occ.grp, bg.grp = bg.grp)
  return(out)
}

**Comment by ndimhypervol** [comment]
I verified Cory's issue. I think we should implement a fix, but a less messy version would be to simple coerce the input, if matrix, to a df. That would require less coercing than the example.

**Comment by bobmuscarella** [comment]
Yeah, I agree.  I think the reason we haven't seen this before is that we have this kind of conversion in at the start of the 'ENMevaluate' function.... if someone uses the partitioning functions separately the it could crop up.  I think we should probably keep the ENMevaluate function as is and add these lines to the partitioning functions as you mention.  I don't think it's necessary for all of the partitioning functions but maybe we should include it for consistency?

**Comment by bobmuscarella** [comment]
Okay, i added these lines to the beginning of the partitioning methods:

  occ <- as.data.frame(occ)
  rownames(occ) <- 1:nrow(occ)
  bg.coords <- as.data.frame(bg.coords)
  rownames(bg.coords) <- 1:nrow(bg.coords)
