### ISSUE TITLE
Error when 'rasterPreds' argument is FALSE

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#4]
I got this error:

Error in { : task 1 failed - "object 'predictive.map' not found"

I think it is because the line where all the results are combined into the final 'results' object (line 153) includes a 'predictive.maps' object and does not have an ifelse switch to deal the rasterPreds=F cases.

**Comment by ndimhypervol** [comment]
Bob, can you test this with the new edits? I think I fixed the problem.

**Comment by bobmuscarella** [comment]
This seems to be fixed.

**Comment by bobmuscarella** [comment]
(Sorry for confusion about closing/reopening issue... )

The error with not generating predictions is now different.

Error in validObject(.Object) : 
  invalid class “ENMevaluation” object: invalid object for slot "predictions" in class "ENMevaluation": got class "NULL", should be or extend class "RasterStack"

I think an easy fix may be to just change the 

predictive.maps <- NULL

to 

predictive.maps <- stack()

**Comment by ndimhypervol** [comment]
Yeah, that sounds like a clean fix.
