### ISSUE TITLE
enmeval crashes r: install java 6

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#40]
On Apr 26, 2016, at 9:36 AM, Cory Merow wrote:

yo - thought you'd like to know that upon installing EMNeval, it crashes r with the message that i need to install Java 6 SE runtime. that's an easy fix, but maybe seems confusing for some users, and it seems like installing a package shouldn't cause R to crash. since you both surely had the right version of java installed, i figured this might be an error you hadn't seen before....
Cory

**Comment by bobmuscarella** [comment]
This seems like a problem with loading rJava.  Not sure if there is anything we can do about it - maybe left to the user... See, e.g.:

http://conjugateprior.org/2014/12/r-java8-osx/

**Comment by ndimhypervol** [comment]
Should we detect the Java version, and if it's old, flag a warning and maybe link that helpful post?

**Comment by bobmuscarella** [comment]
But is sounds like Cory got a warning message that said he needed to install a certain version of Java?  I'm not sure why we need to add another warning that says basically the same thing?  Then we will also have to keep track of which versions of java work and don't work.  I think we can table this for now.

**Comment by ndimhypervol** [comment]
Yeah, Java installation problems are super annoying. What I've found is that you just need to make sure you have the most updated Java version and that the bit number matches your R installation (32 or 64). Maybe we could note this in the vignette and the documentation?

J
