### ISSUE TITLE
Lambdas data frame?

### ISSUE THREAD

**Issue by ndimhypervol** [bobmuscarella/ENMeval#43]
We talked about overwriting the lambdas slot in the Maxent object with a data frame, because the existing one is weird and can't be indexed.

**Comment by bobmuscarella** [comment]
yeah - might as well do this.  Why don't you add what you already made as a separate function and then just call it in one line in the tuning function?  This would probably be cleanest and it would then also be separately available to folks, which might be useful.

**Comment by bobmuscarella** [comment]
Since a script exists for this in the 'rmaxent' package (we are adding this as a 'to do' on the vignette).
