### ISSUE TITLE
option to hide progress bar

### ISSUE THREAD

**Issue by ndimhypervol** [bobmuscarella/ENMeval#45]
This would be nice to include so that we can hide it from the output in the vignette, as I can't figure out a good way to do this without restricting each call of ENMevaluate to its own chunk, which is annoying.

**Comment by bobmuscarella** [comment]
I just edited the tuning() and ENMevaluate() functions to do this.  Hopefully it works.  THere is a new argument in the ENMevaluate function called "progbar".  The default is TRUE but when FALSE it will skip the progress bar parts of the tuning function.  

Hope it works but please test it out.
