### ISSUE TITLE
Checking data format

### ISSUE THREAD

**Issue by ramongallego** [bobmuscarella/ENMeval#48]
Recently I faced an issue with ENMeval, while trying to get it to work with the "user" defined groups. The error message was 
***
Error in rowMeans(AUC.DIFF) :
  'x' must be an array of at least two dimensions
Calls: ENMevaluate -> tuning -> rowMeans
Execution halted
****
I finally solved it, the problem was that the occ.grp object must be a vector, and I was providing a dataframe (as I imported a .csv with the locations). So in case something similar happens to anyone, maybe it will be possible to include a step in the ENMevaluate formula in which the structure of the input data is checked

**Comment by bobmuscarella** [comment]
Thanks for that, Ramon.

I think we can add something like the following to the first line of the 'get.user' function: 

`if(class(occ.grp) == 'data.frame' | class(bg.grp) == 'data.frame'){
warning('Please supply occ.grp and bg.grp as vector objects.')
}`

It'd be nice to just convert but I'm kind of afraid that we may open more potential bugs by trying to wrongly convert something... Please let me know if someone has a better fix.

Bob

**Comment by bobmuscarella** [comment]
I added this line to the `get.user` function:

```{r}
if(class(occ.grp) == 'data.frame' | class(bg.grp) == 'data.frame'){ 
warning('For user-defined groups, occ.grp and bg.grp must be supplied as vectors.') 
}
```
