### ISSUE TITLE
Errors in parallel runs

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#5]
1) I got this error when doing parallel=T with the example script

Error in { : task 37 failed - "sink stack is full"

This may be useful:
http://stackoverflow.com/questions/8339306/sink-inside-a-for-loop-gives-the-error-sink-stack-is-full-in-r

2) Also, when I turn parallel off (parallel=F) i get this list of warnings:

2: closing unused connection 8 (<-localhost:11257) 
3: closing unused connection 7 (<-localhost:11257) 
4: closing unused connection 4 (<-localhost:11257) 
5: closing unused connection 3 (<-localhost:11257) 
6: closing unused connection 6 (<-localhost:11257) 
7: closing unused connection 5 (<-localhost:11257)

**Comment by ndimhypervol** [comment]
I added a sink() after the first sink call, which I think fixes this. Also, I close the connections in the script, so you probably won't get those warnings anymore.

**Comment by bobmuscarella** [comment]
Okay, when parallel=F, no errors.  So, I guess this is fixed.

But, now I get a different error when parallel is turned on:

Error in validObject(.Object) : 
  invalid class “ENMevaluation” object: invalid object for slot "predictions" in class "ENMevaluation": got class "NULL", should be or extend class "RasterStack"

This kills the operation and no object is returned...

**Comment by bobmuscarella** [comment]
Yes, this seems to have fixed the problem

**Comment by bobmuscarella** [comment]
Yes, this seems to have fixed the problem
