### ISSUE TITLE
Compatibility with maxnet

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#52]
- Make maxnet the default and optional Maxent java
- Make a switch for running dismo::maxent vs. maxnet functions
- Make functions for extracting and organizing results
- Add function to change predicted data.frame to a raster
- Edit documentation / warnings to tell user about output values / version + program being used
- Move rJava to suggests

**Comment by ndimhypervol** [comment]
Started work on this. Made new branch `maxnet`, and rearranged some stuff: 
- made modelTune() the new tuning() to avoid name confusion, and broke it off into a separate script; it's meant to work for either parallel or not
- added new function to make raster predictions from maxnet objects (otherwise, they are data frames)
- added some code to automatically report how many rows for occs and bg have NA for predictor vars, and then take them out; this is a big issue for maxnet, as it errors if there are any NAs

If you guys have any <issues> with this stuff, just holler.

**Comment by bobmuscarella** [comment]
Nice! 
But are we going to run the risk of breaking other codes by changing the name of the tuning function?

**Comment by ndimhypervol** [comment]
That shouldn't be an issue unless people are running tune() outside the tuning() function, which in turn would be outside ENMevaluate(). These are internal functions, so nothing should break.

**Comment by Pgalante** [comment]
I use tuning on its own with silly changes, but this would only change the reproducibility of that code.

**Comment by ndimhypervol** [comment]
Please try `install_github('bobmuscarella/ENMeval@maxnet')`, load it up, and test between `java=TRUE` and the default `java=FALSE`. The package is functional, but I am seeing some very strange results from maxent.jar 3.4, and when comparing them with 3.3.3k, they are quite different. Have you done any testing to compare these two?

**Comment by ndimhypervol** [comment]
So it looks like when running `maxent()`, there is no issue, but something ENMeval does is making the results look weird for v 3.4. Will investigate later.

**Comment by Pgalante** [comment]
I found a difference between using x= rasters and p= coordinates instead of extracting the values and appending 1s and 0s.

**Comment by ndimhypervol** [comment]
When running maxent() you mean?

**Comment by Pgalante** [comment]
Yes. Using Maxent() gives different results (between 3.3.3 and 3.4) only when using rasters and a dataframe of coordinates.

**Comment by ndimhypervol** [comment]
Okay that is very odd. Have you found also that occasionally 3.4 will give completely flat (AUC 0.5) results? You need to reload dismo in a fresh R session to make it work again. I have had that happen many times. Can we try to get some scripts together that reproduce these problems and send them to Steven?

**Comment by ndimhypervol** [comment]
Tested new Maxent 3.4.1 and it seems to work fine now. Function `maxnet()` works as well. I have a functional version of ENMevaluate with new param `algorithm` that needs a little testing. Would you guys be able to test it at some point?

Importantly, I've restructured things so that it'll be easier to add new algorithms in the future. Please let me know what you think.

**Comment by bobmuscarella** [comment]
Jamie has made a lot of progress with code to implement the 'maxnet' algorithm and I've been updating the documentation.  I think the things to do before pushing to CRAN are:
1. Deal with the fact that the ENMevaluation object 'model' slot differs if you use the 'maxnet' or 'maxent.jar' algorithm.  Can we identify potential issues with this?  (e.g., the 'var.importance' function does not seem to work with the 'maxnet' output).
2. Finish documentation updates (Bob)
   - Address the point above
   - Add aliases of the new functions to existing documentation 
   - ...?
3. Update the vignette to include the 'maxnet' stuff (as well as other vignette updates in issue #53 (Bob)
4. Anything else?

**Comment by ndimhypervol** [comment]
I think `var.importance()` is the only thing currently affected by the different in model objects. The `predict.maxnetRas()` function does `predict()` for maxnet objects and produces a raster. The `response.maxnet()` function returns the values needed to plot a response curve from a maxnet object (because the `maxnet::response.plot()` function does not work the way it's supposed to when you ask to return the values (until Steven fixes it?). Working on figuring out how to get variable importance for maxnet models right now.

**Comment by ndimhypervol** [comment]
So variable importance will be tricky for `maxnet` because it may not be so straightforward for `glmnet` models, which `maxnet` is based on. I say we table this for now and restrict  `var.importance()` to Maxent models because we have the information there already. The other functions I developed give the maxnet models some core functionality, and I say we add more features for these models as time progresses. Can we get the ball rolling on putting out the new version? Seems like documentation is the big hurdle left.

**Comment by bobmuscarella** [comment]
I agree and I have finished most of the documentation changes.  There are a few points we should discuss (let me know if you want to schedule a time to Skype):

**1.** I think we need to add documentation for the functions you created:
`maxentJARversion.R`
`modelTune.maxentJar.R`
`modelTune.maxnet.R`
`predict.maxnetRas.R`
`response.maxnet.R`

You did already added an .Rd file for response.maxnet.R, which I did not change.  For now, I gave all the others a single documentation file (`maxnet.functions.Rd`).  We may want to give `predict.maxnetRas.R` it's own documentation because people may want to use that function whereas the others are really for internal use only.

**2.** The other thing obviously different between the maxent/net implementations is the @model slot of the ENMevaluation object class.  I made some edits to this documentation but they are minimal.  I'm not so clear on interpretation and downstream use of the maxnet model output; we could eventually do more to help make this clear and offer some examples in the documentation on how to use these outputs.

**3.** After doing this I was trying to build and test the package.  I got an error in the creating vignette step.  I think maybe we need to specify that package version to download from Github is the 'maxnet' branch, at least until be push that to the master branch.  Here is the output:

d28582:GIT au529793$ R CMD BUILD ENMeval
* checking for file ‘ENMeval/DESCRIPTION’ ... OK
* preparing ‘ENMeval’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
Loading required package: spocc
Loading required package: ENMeval
Loading required package: sp
Loading required package: maptools
Checking rgeos availability: TRUE
Loading required package: rgeos
rgeos version: 0.3-26, (SVN revision 560)
 GEOS runtime version: 3.6.1-CAPI-1.10.1 r0 
 Linking to sp version: 1.2-5 
 Polygon checking: TRUE 

Warning in gBuffer(ca.sa, width = 1) :
  Spatial object is not projected; GEOS expects planar coordinates
Warning in randomPoints(envs.backg[[9]], n = 10000) :
  generated random points = 0.56 times requested number
Quitting from lines 317-320 (ENMeval-vignette.Rmd) 
Error: processing vignette 'ENMeval-vignette.Rmd' failed with diagnostics:
no slot of name "algorithm" for this object of class "ENMevaluation"
Execution halted
d28582:GIT au529793$

**Comment by bobmuscarella** [comment]
Following up on the point involving the vignette:

I tried to run through the vignette and recreate the example output data in order to save this again with the new format of the ENMevaluation object.  I run into a problem, however, that that step when running the vignette code (section ***Running ENMeval***).  It works as expected with `algorithm = 'maxent.jar'` but not for `algorithm = 'maxnet'`:

**For maxent.jar**
```
> eval1 <- ENMevaluate(occs, envs, bg, method='checkerboard2', RMvalues=c(1,2), fc=c('L'), algorithm = 'maxent.jar')
Loading required namespace: rJava
*** Running ENMevaluate using Maxent 3.3.3k via dismo 1.1.4 ***
Doing evaluations using checkerboard 2...
There are 2 background records with NA for at least one predictor variable. 
                  Removing these records from analysis, resulting in 5600 records...
  |======================================================================================| 100%
ENMeval completed in 0 minutes 11.7 seconds.
```

**For maxnet**
```
> eval1 <- ENMevaluate(occs, envs, bg, method='checkerboard2', RMvalues=c(1,2), fc=c('L'), algorithm = 'maxnet')
*** Running ENMevaluate using maxnet v.0.1.2 ***
Doing evaluations using checkerboard 2...
There are 2 background records with NA for at least one predictor variable. 
                  Removing these records from analysis, resulting in 5600 records...
  |===========================================                                           |  50%
 10 grid cells found with at least one NA value: these cells were not processed.
Error in m[p == 1, ] : (subscript) logical subscript too long
```

**Comment by bobmuscarella** [comment]
I've been working on this and now, for some reason, ENMeval fails to execute maxnet models when hinge features are included.

```R
library(devtools)
install_github("bobmuscarella/ENMeval", ref='maxnet')

library(ENMeval)
library(raster)    # For some reason raster is not automatically loading??

### Simulated data environmental covariates
set.seed(1)
r1 <- raster(matrix(nrow=50, ncol=50, data=runif(10000, 0, 25)))
r2 <- raster(matrix(nrow=50, ncol=50, data=rep(1:100, each=100), byrow=TRUE))
r3 <- raster(matrix(nrow=50, ncol=50, data=rep(1:100, each=100)))
r4 <- raster(matrix(nrow=50, ncol=50, data=c(rep(1,1000),rep(2,500)),byrow=TRUE))
values(r4) <- as.factor(values(r4))
env <- stack(r1,r2,r3,r4)
### Simulate occurrence localities
nocc <- 50
x <- (rpois(nocc, 2) + abs(rnorm(nocc)))/11
y <- runif(nocc, 0, .99)
occ <- cbind(x,y)

bg.coords <- dismo::randomPoints(env, 500)

### Try doing this with the Maxnet algorithm
res.ENMeval.maxnet <- ENMevaluate(occ, env, bg.coords=bg.coords, 
                                  method="block", n.bg=500, algorithm="maxnet", 
                                  RMvalues=1:2, fc=c("L","H"))


### FOR ME, THIS RETURNS THE FOLLOWING:

*** Running ENMevaluate using maxnet v.0.1.2 ***
Doing evaluations using spatial blocks...
  |===========================================                                           |  50%Error in mm %*% object$betas : non-conformable arguments

### I only seem to get this error if hinge features are included.

### It seems that I can do it in the native maxnet way without getting the error.  The following lines run without any warnings/errors.

> p <- c(rep(1, nrow(occ)), rep(0, nrow(bg.coords)))
> x <- data.frame(rbind(extract(env, occ), extract(env, bg.coords)))
> res.maxnet <- maxnet::maxnet(p, 
+                            data=x, 
+                            f = maxnet::maxnet.formula(p = p, data = x, classes = 'lh'), 
+                            regmult = 1:2)

```

**Comment by ndimhypervol** [comment]
I don't get this error with the data from the vignette. Maybe due to the way you generated occurrence points? Switching to the bradypus points and the envs associated doesn't error for me.

**Comment by bobmuscarella** [comment]
Lots of issues wrapped up here...
