### ISSUE TITLE
Omission of points in get.checkerboard2 (from Yoni Gavish)

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#54]
Dear Robert, 

Thanks for creating and maintaining the ENMEval package! 

I'm using it to create the cross-validation sets for an analysis of 2.5 million records of 236 tree species covering approximately 5 million 1 *1 km pan-European cells (the actual maxent modeling is done in the 'maxnet' package).

I've encountered an issue U thought you should know about:
When applying the 'get.checkerboard2()' , some of the presences and background points are being omitted, especially for species that have an highly aggregated pattern or species that are very common. 
It happens since the function sets an upper limit when calling 'dismo::gridSample', e.g.:
gridSample(occ, grid, n = 10000, chess = "white")
It does not happen (in my case) in the 'get.checkerboard1()', where n is set internally to 1e+06. 
Using a modified version of the 'get.checkerboard2()' where 'n' is controlled as another function parameter, and setting n= 20000 seems to work in my case. 

Anyhow,  If you are planning a new version for the package, it would be great if you could set 'n' as another parameter in function call. 

Best regards and thanks again for this excellent package!

Yoni
---------------------------------------------------------------------------------------
Dr. Yoni Gavish
---------------------------------------------------------------------------------------
Research Associate                                                                   
School of Geography, Faculty of Environment, University of Leeds, Leeds, LS2-9JT, UK    
Skype:     yonigavish    ;    twitter:    @GavishYoni    
---------------------------------------------------------------------------------------

**Comment by bobmuscarella** [comment]
Yoni followed up with:

> Hi Bob, 
> Happy to hear you will be implementing 'maxnet'. 
> You probably know about it, but if not, It's worse having a look at 'enmSdm::trainMaxNet'  (https://github.com/adamlilith/enmSdm/).
> I've been using it to run the parameter sweep step. 
> 
> Best regards,
> Yoni

**Comment by ndimhypervol** [comment]
Dr. Yoni,

We've made n a parameter you can change for get.checkerboard2 in the latest version. Thanks.
