### ISSUE TITLE
Error in unserialize(socklist[[n]]) : error reading from connection

### ISSUE THREAD

**Issue by jtonini** [bobmuscarella/ENMeval#61]
Loading required namespace: rJava
*** Running ENMevaluate using Maxent 3.4.1 via dismo 1.1.4 ***
Doing evaluations using checkerboard 2...
Of 32 total cores using 8
Running in parallel...
Error in unserialize(socklist[[n]]) : error reading from connection
Calls: ENMevaluate ... recvOneData -> recvOneData.SOCKcluster -> unserialize
Execution halted

**Comment by bobmuscarella** [comment]
I haven't seen this error before but it seems to be an issue with the mechanics of running parallel that goes beyond the scope of ENMeval itself ([check out the hits from this quick google search on that error message](https://www.google.dk/search?q=Error+in+unserialize(socklist%5B%5Bn%5D%5D)+%3A+error+reading+from+connection&rlz=1C5CHFA_enDK768DK768&oq=Error+in+unserialize(socklist%5B%5Bn%5D%5D)+%3A+error+reading+from+connection&aqs=chrome..69i57j69i64.244j0j7&sourceid=chrome&ie=UTF-8)). Have you tried other parallel operations on your machine?  Best of luck in figuring this out but it does not appear to be related to ENMeval code, per se, so I am closing the issue.

**Comment by jtonini** [comment]
The parallel option works fine on my personal computer but when running on the hpc results in this error. Before I post this issue I was talking to the IT staff and they suggested it might be an issue with the way the function suppose to interact with java. Thanks for the feedback.

**Comment by Pgalante** [comment]
I was getting similar errors using a Linux machine. This might explain the error on the hpc.  I have not been able to find a fix- my best guess was it seems to be a bug between Linux and R (for me Ubuntu 18.04, R 3.5.1). Do you know what type of Linux the hpc is running? What version of R?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jtonini** [comment]
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core

R/3.5.1
