### ISSUE TITLE
Grid cells found with at least one NA value: these cells were excluded from raster predictions.

### ISSUE THREAD

**Issue by nhelm** [bobmuscarella/ENMeval#65]
Hi,

I have been running multiple models with ENMeval to optimize RM values. I am using a 'user' defined partition method. I have locations and background points binned into geographically distinct areas. When I run ENMeval using algorithm = 'maxnet', every time it updates the progress bar (10%, 20%, 30%, etc...) it shows this warning:

10 grid cells found with at least one NA value: these cells were excluded from raster predictions.

When I use algorithm = 'maxent.jar' I never seem to see this error. Also, I added raster values from all my environmental variables to my location and background points and there are no NA values. Any ideas on why this warning keeps showing up? I pasted my code below.

Thanks,

Nolan 

global_2fold<-ENMevaluate
  occ=lcts_2fold,
  env=global_2fold,
  bg.coords=bkgd_2fold,
  occ.grp=bin_2fold$occ.grp,
  bg.grp=bin_2fold$bg.grp,
  RMvalues = seq.int(0.1,10,0.1),
  fc=c("LQH"),
  algorithm='maxnet',
  categoricals='lndcvr_fin',
  n.bg=NULL, 
  method='user',
  overlap = FALSE, 
  aggregation.factor = NULL,
  kfolds=NULL,
  bin.output = TRUE
  clamp = FALSE,
  rasterPreds= TRUE)

**Comment by ndimhypervol** [comment]
Hey Nolan,

It might be because there is one or more rasters in your stack that has cells with NA, and these same cells have non-NA values for the other rasters. If you did not use the raster with more NAs to sample your background points, you might end up with points on these cells. Try masking the stack by the offending raster and see if that fixes your problem.

Jamie

**Comment by nhelm** [comment]
Hey Jamie,

Thanks for responding. I'm impressed by the number of people you respond to (I'm frequently on the Maxent Google Groups as well).

I'm fairly certain that isn't the issue. I just double checked the raster values at all my background and location points and there are no NAs (I extracted values to points using ArcMap). I'm not randomly selecting background points since I'm using a user-defined partition so each time I run the model it is using the same background points. 

I'm wondering if maybe it's getting thrown off for values that are either very close to 0 or negative? Two of my variables are sine and cosine of aspect (I wanted to avoid using a circular variable). I'll keep trying to tease out which variable it is having issues with, and update if I figure anything out.

Thanks,

Nolan

**Comment by nhelm** [comment]
Hey Jamie,

So I figured it out (you were basically right), I was just confused by the error. I thought it meant my background points had NAs (i.e. they were located on cells without values) but it was just referencing raster cells that had NAs and had nothing to do with my background points. I masked all my variables by each other and then extracted values to my background points and there were still no NAs, however, the model ran without errors. I must've had some cells in one of those variables I forgot to mask! Anyway, sorry for the confusion and thanks for the help. 

Also, I posted a question on the Maxent google groups, but perhaps if you have time you could help me here.

I really like the fact that ENMeval allows users to define background/occurrence partitions. I optimized my RM value using ENMeval with LQH feature classes and would now like to use that optimized model to project to new areas. However, I would like to be able to view my lambdas, possibly increase the iterations from 500 to something greater, create a MESS map, and explore different clamping options (fade by clamping, clamp, and do not extrapolate) all while continuing to use the 'user defined' partitions. I realize I could run ENMeval using Maxent.jar, but the hinge feature class has different "knots" in Maxnet vs Maxent (maxnet: 50 hinge features evenly spaced, Maxent: one knot per unique value of an environmental variable). Any suggestions on this issue? If I can define the knots in Maxent.jar all my problems would be solved but I haven't seen that option anywhere! 

Thanks, I realize the above isn't really an "issue" with ENMeval, but I'd appreciate any advice.

Nolan

**Comment by ndimhypervol** [comment]
Hey Nolan, just answered your question in the Maxent Google Group. Regarding hinge features, you're right about the limitation in maxnet, but it shouldn't make a huge difference. You cannot specify knot parameter changes in Maxent from what I understand.

Also glad you figured out the issue with the NAs. In the upcoming version of ENMeval, I'll make sure this is fixed.

**Comment by nhelm** [comment]
Hey Jamie,

So I think the differences in the knot features are going to be a bit of a pain! After determining an optimal model (RM value) using ENMeval(...algorithm='maxnet'), I re-ran the optimal model using ENMeval(...algorithm='maxent.jar'). Test AUCs were roughly the same but it added about 100 parameters to the model! I'm assuming that is because of all the extra hinge parameters.

At this point, I'm a little confused as to what direction to take. I'd like to continue using the 'maxnet' algorithm to be consistent (along with user-defined partitions in ENMeval), but would also like to be able to plot response curves and view the prediction map as logistic (predict(model@models[[1]],env) doesn't work via maxnet in ENMeval). 

Has anyone had any luck with the predict.maxnetRas() or response.maxnet() functions that you all were discussing here https://github.com/bobmuscarella/ENMeval/issues/52?

Thanks again for helping to keep the Maxent community sane!

Nolan

**Comment by ndimhypervol** [comment]
Glad our functions worked for you. Yes, if you would like a prediction bounded by 0,1 and can live with the assumptions, either logistic or cloglog could be good choices. The Phillips et al 2017 paper makes the case for cloglog.

Regarding the knots, it might make for a smoother curve, but should not change the response all that much (just add many more parameters). The geographic prediction should look nearly the same.

Jamie
