### ISSUE TITLE
warning when NA for env val?

### ISSUE THREAD

**Issue by ndimhypervol** [bobmuscarella/ENMeval#7]
Wondering if we should put in a warning, as it results in weird things like NAs in the results table for threshold stats sometimes.

**Comment by bobmuscarella** [comment]
I think that's a fine idea.  I added some lines after lines 24-26 of the tuning function where 'pres' and 'bg' data frames are first created.  See if you think that's adequate.

**Comment by bobmuscarella** [comment]
Just a note about this that we may consider putting somewhere in documentation:

When background points are selected using randompoints function, it arbitrarily uses the first environmental layer as a grid from which to pull points.  It won't pull points from NA cells so the NA in environmental layers is not an issue for background points in the first environmental layer.  If there are different cells with NA values in the other layers the problem can pop up.  it can also, of course, pop up for presence points.

**Comment by ndimhypervol** [comment]
Yeah, that's a bigger problem though, because predict() will also malfunction if some rasters have NULL cells where others don't. Perhaps a different warning, or an error, is in order for that? I can work on that later. Assuming that isn't a problem, your current warnings are fine, I think.

**Comment by bobmuscarella** [comment]
This is done = just add notes to documentation
