### ISSUE TITLE
Unable to run ENMevaluate with hinge features

### ISSUE THREAD

**Issue by MiguelRFerreira** [bobmuscarella/ENMeval#72]
Hello everyone,

I have been trying to run ENMevaluate for several species with few occurrence records (min: 10; max: 28) and all the models with hinge features (H, LH, PH, QH, LQH, PQH, LPQH) do not result in any output (NA in the "results" table).

However, running the models with these feature classes in Maxent GUI results perfectly. Do you know what could be wrong?

I leave the code below:

ENMevaluate(occ=occs,
                       env=envs,
                       method='randomkfold',
                       kfolds=10,
                       bg.coords = bg,
                       RMvalues = c(seq(0.1,1,0.1),1.5,2, 3),
                       fc =   c("L", "P", "Q","H", "LP", "LQ", "LH", "PQ", "PH", "QH", "LPQ", "LPH", "LQH", "PQH","LPQH"),
                       algorithm='maxent.jar',
                       bin.output=T,
                       clamp=F,
                       rasterPreds=T,
                       parallel=T,
                       overlap=F)

**Comment by Pgalante** [comment]
Hi Miguel,
It's hard to know exactly, but the issue might be related to the number of parameters used by those models. ENMeval does not report AICc results for models made with more (or the same) parameters than occurrence records - which happens fairly often when using Hinge features and few occurrence records. You can usually constrain the parameters using a higher regularization multiplier.

Another guess is that using 10 random k folds for 10 (or very few) occurrence records is causing some models to not be created (Can't build models on 1 occurrence record?). When these model stats get averaged, it likely runs everything NA.

Try increasing the RMvalues and see if that helps?

**Comment by MiguelRFerreira** [comment]
Yes, indeed with higher regularization multipliers this problem does not occur, even when I reduce the number of random k folds.

Thank you very much for your help!

**Comment by ndimhypervol** [comment]
Yes, running Maxent with very low regularization (below 1) and hinge features usually leads to an overfit model with many parameters, resulting from a very close fit to your data. This can end in error (especially for maxnet) because of issues with model convergence. If you include only several variables, the model might converge but you will likely still have problems with overfitting. A good way to check on overfitting is to inspect AUCdiff and OR values using spatial cross-validation.
