### ISSUE TITLE
Add functionality for doParallel as well as doSNOW

### ISSUE THREAD

**Issue by ndimhypervol** [bobmuscarella/ENMeval#76]
There are apparently issues with doSNOW on supercomputers.

**Comment by elgabbas** [comment]
I think that at some point I had a similar issue when running on a HPC. I had to change a couple of ENMeval functions myself.

**Comment by ndimhypervol** [comment]
Well, hope this remedies things for others in a similar situation. Thanks
for the input, Ahmed.
-----------------------------------------------------------
Jamie Kass, Ph.D.
Biodiversity and Biocomplexity Unit
Okinawa Institute of Science and Technology
Institutional email: jamie.kass@oist.jp
<http://andersonlab.ccny.cuny.edu>

**Comment by ndimhypervol** [comment]
Closing this as it's been added to v2.0.
