### ISSUE TITLE
Error in { : task 12 failed - "non-conformable arguments"

### ISSUE THREAD

**Issue by momeni133** [bobmuscarella/ENMeval#79]
Hello everyone,
Since upgrading to R 3.6.3 whenever I try to run "ENMevaluate" function, I receive the below error. Do you know how to solve this problem?

> Error in { : task 12 failed - "non-conformable arguments"

**Comment by ndimhypervol** [comment]
Not sure, but why don't you try downloading the development version on the "dev" branch with devtools::install_github("bobmuscarella/ENMeval@dev"). Hopefully this will fix the problem. The syntax for running the function may be slightly different, so check the documentation.

**Comment by momeni133** [comment]
Thanks. I tried but here is the error I receive from the development version:

> Error in { : task 1 failed - "could not find function "modelTune.maxnet""

**Comment by ndimhypervol** [comment]
Can you please copy-paste the function call to ENMevaluate() you are trying
to run? Thanks.

**Comment by momeni133** [comment]
Sure.
Here it is:
`results.A <-ENMevaluate(occs = occ, bg.coords = background, envs = predictorsEW, mod.nam = "maxnet",
                                           method = "checkerboard2", overlap = FALSE, RMvalues= seq(0.5,10,0.5), fc = c("L","H", "LQ", "LQH", "LQHP"),
                                           bin.output = FALSE, parallel = TRUE, rasterPreds = TRUE)`

**Comment by ndimhypervol** [comment]
First off, mod.name is spelled wrong. Is that the issue?

-----------------------------------------------------------
Jamie Kass, Ph.D.
Biodiversity and Biocomplexity Unit
Okinawa Institute of Science and Technology
Institutional email: jamie.kass@oist.jp
<http://andersonlab.ccny.cuny.edu>

**Comment by momeni133** [comment]
Sorry for the typo.
It didn't solve the problem. After correcting the mod.name, the error is changed to:
> Error in ENMevaluate(occs = occ, bg.coords = background, envs = predictorsEW,  : 
> * For checkerboard partitioning, predictor variable rasters "envs" are required.


I am sure that my "envs" layers are correct (it is a RasterStack). I was using this code before upgrading my R without any problems.

**Comment by ndimhypervol** [comment]
Thanks for catching this bug. You should only get this error when "envs" is NULL and one of the checkerboard partitions is selected. The problem is that "rasterPreds" was deprecated, and the error catch was wrong. I fixed this so that when you include "rasterPreds" it informs you that the parameter is deprecated. Please pull the newest version for this change. But if you simply remove "rasterPreds" from the function call, it should run fine.

**Comment by momeni133** [comment]
Hi Jamie,
Thanks. I have updated it to the latest version.
Now, I receive the below error again:

> Error in { : task 1 failed - "could not find function "modelTune.maxnet""

**Comment by ndimhypervol** [comment]
You seem to be loading the old version of ENMeval (v0.3). Did you run devtools::install_github("bobmuscarella/ENMeval@dev")? Perhaps start a new RStudio session and do library(ENMeval) again.

**Comment by momeni133** [comment]
After closing and re-opening the rstudio the error has changed to:

> * Running ENMeval v1.0.0 with legacy parameters. These will be phased out in the next version.

> Error in ENMevaluate(occs = occ, env = predictorsEW, bg.coords = background,  : 

>   This parameter was deprecated. If you want to avoid generating model prediction rasters, include predictor variable values in the occurrence and background data frames (SWD format). See Details in ?ENMevaluate for more information.

Also when I try ?`ENMevaluate `it seems that the documentation has gone (even after re-installing the package)

**Comment by ndimhypervol** [comment]
Yes, you need to remove the "rasterPreds" parameter from the call in order
for it to function.
-----------------------------------------------------------
Jamie Kass, Ph.D.
Biodiversity and Biocomplexity Unit
Okinawa Institute of Science and Technology
Institutional email: jamie.kass@oist.jp
<http://andersonlab.ccny.cuny.edu>

**Comment by momeni133** [comment]
Thanks a lot Jamie.
The problem has been solved!

**Comment by ndimhypervol** [comment]
Great news!
