### ISSUE TITLE
Model objects added to output do not include HTML file

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#8]
I guess this is because the maxent model object just holds the path to the html file rather than the file itself.  When the model objects are saved into the ENMevaluation object, the other values (lambdas, results, etc.) are saved.  The path to the HTML file is saved but the file has been deleted by that time.  

I suppose we can deal with this in 1 of 2 ways:

1) Include this issue in the documentation.  If users want the html file, they should rerun things with dismo or with the maxent interface.

2) We could add some code for the user to designate a path to save ALL the maxent output generated in a run.  This might be useful in some cases and it could be good for total transparency although I would recommend against it usually since it can eat up a lot of memory.  I guess they would provide a path and then we would write maxent output files for each setting in its own sub folder.  this would be easy with the non-parallel version but i'm not sure about the parallel version...

What do you think?

**Comment by ndimhypervol** [comment]
I think with all the functions in dismo and the slots in the model object, the html is mostly obsolete. Thus, we could comment on this in the documentation and say that if you want it, please run maxent in dismo. But if you're strongly for providing the user the html's, we can figure out a way to do it.

**Comment by bobmuscarella** [comment]
I agree that the html file is mostly obsolete but it does have some conveniences... like if you want to quickly visualize what the response curves look like, for example.  I don't feel too strongly that an option to save all maxent output should be included in this version but i guess I would add it to the longer term to do list.

**Comment by bobmuscarella** [comment]
This will stay on hold - 
We can add a section to vingette on how to get response curves and other stuff from model objects.
