### ISSUE TITLE
Run ENMevaluate using "p" and "data" as in maxnet, instead of "occ" and "env"

### ISSUE THREAD

**Issue by hgfell** [bobmuscarella/ENMeval#80]
This is definitely a question not an issue.
 
Is there currently a method to use presence and absence points as a vector (p) and environmental data (data), as you would through the maxnet function when used independently, through ENMevaluate?

I am working with data which are unfeasble to represent as rasters but I can extract the relavent data to use  the "p" and "data" objects from the maxnet function. 

`maxnet(p, data, f = maxnet.formula(p, data), regmult = 1, 
       regfun = maxnet.default.regularization, ...)`

I was hoping I may be able to use ENMevaluate with the maxent function, however I cannot find any way of inputing the data as in the maxent function instead of using raster objects.

Thanks

Henry

**Comment by ndimhypervol** [comment]
Please install the dev version of ENMeval in the "dev" branch. Run the following code:

devtools::install_github("bobmuscarella/ENMeval@dev")

There is an option to run without rasters if you provide the predictor variable values in the input data frames. See the examples in the vignette.

**Comment by bobmuscarella** [comment]
Ha!  @ndimhypervol is very fast!   I was typing to suggest the same thing.
Good luck!

**Comment by hgfell** [comment]
Great, Thanks for replying so quick, I clearly hadnt looked through the vignette enough.
