### ISSUE TITLE
[dev] Bug in parallel option enm.pkgs

### ISSUE THREAD

**Issue by gepinillab** [bobmuscarella/ENMeval#84]
Hi @ndimhypervol,

I got this error after using parallel option on Wallace. Dev branch was updated.

Running in parallel using doSNOW...
Warning: Error in enm.pkgs: could not find function "enm.pkgs"
  79: foreach::foreach [C:/Users/Gonzalo/Desktop/github/ENMeval/R/tune.enm.R#142]
  76: tune.parallel [C:/Users/Gonzalo/Desktop/github/ENMeval/R/tune.enm.R#142]
  75: ENMeval::ENMevaluate [C:/Users/Gonzalo/Desktop/github/ENMeval/R/ENMevaluate.R#354]
  74: model_maxent [C:/Users/Gonzalo/Desktop/github/wallace/R/model_maxent.R#133]
  73: observeEventHandler [C:\Users\Gonzalo\Documents\R\win-library\4.0\wallace\shiny\modules\model_maxent.R#119]
   2: shiny::runApp
   1: run_wallace [C:/Users/Gonzalo/Desktop/github/wallace/R/run_wallace.R#23]

Best,
Gonzalo

**Comment by ndimhypervol** [comment]
Can you please pull and try this again. I had removed the pkgs slot for ENMdetails because i don't think we need them, and so I removed the .packages arg for foreach(). Not sure if this is essential or not, but it works on my machine. Please give this a quick test and let me know if it's okay.

**Comment by gepinillab** [comment]
It is working again. Thanks!
