### ISSUE TITLE
Break up 'tuning' function?

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#9]
Since adding parallelization, the tuning function is pretty long.  What do you think about placing the 'tune' function (which preps for parallelization) as a separate function?  It could be documented in the same page as the tuning function.  If we do this, we might consider renaming it "parallel_tune" or something like that...  

thoughts?

**Comment by ndimhypervol** [comment]
Yeah, I'm always for breaking up big functions when it makes sense. I was wondering about this same thing as I was writing the parallel stuff. I like "parallel_tuning" and "tuning". A simple if/then should be enough to wire it up.
